name: CI Pipeline & Docker Build

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
      - '.github/workflows/**'

env:
  MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML.mlflow
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  REPO_OWNER: ${{ secrets.DAGSHUB_USERNAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas numpy scikit-learn matplotlib seaborn virtualenv

    - name: Train Model & Save Local Artifacts
      working-directory: ./MLProject
      env:
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }} 
      run: |
        python modelling.py

    - name: Verify Model Output
      working-directory: ./MLProject
      run: |
        if [ ! -d "model_output" ]; then
          echo "FATAL ERROR: Folder 'model_output' tidak ditemukan. Training gagal menyimpan model."
          exit 1
        fi
        echo "Model output found. Proceeding to Docker build..."

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML.mlflow
      run: |
        mlflow models build-docker \
          -m "./MLProject/model_output" \
          -n "${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest"

        docker tag ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:${{ github.sha }}

    - name: Push Docker Image
      run: |
        echo "Pushing 'latest' tag..."
        docker push ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest
        
        echo "Pushing unique SHA tag (${{ github.sha }})..."
        docker push ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:${{ github.sha }}