name: CI Pipeline & Docker Build

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
      - '.github/workflows/main.yml'

env:
  MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML.mlflow
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  REPO_OWNER: ${{ secrets.DAGSHUB_USERNAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas numpy scikit-learn matplotlib seaborn virtualenv

    - name: Train Model & Generate ID
      working-directory: ./MLProject
      env:
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }} 
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        python modelling.py

    - name: Check File Existence
      working-directory: ./MLProject
      run: |
        ls -la
        if [ ! -f "last_run_id.txt" ]; then
          echo "FATAL ERROR: Script modelling.py GAGAL membuat file last_run_id.txt"
          exit 1
        fi

    - name: Read Run ID
      working-directory: ./MLProject
      id: get_run_id
      run: |
        run_id=$(cat last_run_id.txt)
        echo "Detected Run ID: $run_id"
        echo "RUN_ID=$run_id" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image from Local Model
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML.mlflow
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        echo "Checking local model folder..."
        ls -R MLProject/model_output
        
        if [ ! -d "MLProject/model_output" ]; then
          echo "FATAL ERROR: Folder model lokal tidak ditemukan!"
          exit 1
        fi
        
        echo "Building Docker Image directly from local folder..."
        
        mlflow models build-docker \
          -m "./MLProject/model_output" \
          -n "${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest" \
          --enable-mlserver

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest